package dev;

public enum AllMethods {
    getNumberOfUniqueIPs,
    getUniqueIPs,
    getIPsForUser,
    getIPsForEvent,
    getIPsForStatus,
    getAllUsers,
    getNumberOfUsers,
    getNumberOfUserEvents,
    getUsersForIP,
    getLoggedUsers,
    getDownloadedPluginUsers,
    getWroteMessageUsers,
    getSolvedTaskUsers,
    getSolvedTaskUsersNum,
    getDoneTaskUsers,
    getDoneTaskUsersNum,

    getDatesForUserAndEvent,
    getDatesWhenSomethingFailed,
    getDatesWhenErrorHappened,
    getDateWhenUserLoggedFirstTime,
    getDateWhenUserSolvedTask,
    getDateWhenUserDoneTask,
    getDatesWhenUserWroteMessage,
    getDatesWhenUserDownloadedPlugin,

    getNumberOfAllEvents,
    getAllEvents,
    getEventsForIP,
    getEventsForUser,
    getFailedEvents,
    getErrorEvents,
    getNumberOfAttemptToSolveTask,
    getNumberOfSuccessfulAttemptToSolveTask,
    getAllSolvedTasksAndTheirNumber,
    getAllDoneTasksAndTheirNumber
}